# Generated by Django 3.1.7 on 2021-08-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20210817_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('BOAT', 'Boat'), ('CARAVAN', 'Caravan'), ('CAR', 'Car')], default='BOAT', max_length=8),
        ),
    ]
