# Generated by Django 3.1.7 on 2021-08-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='v_image',
            field=models.ImageField(default='defaultVehicle.jpg', upload_to=''),
        ),
    ]
