# Generated by Django 3.1.7 on 2021-08-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auto_20210819_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='tripDetails',
            field=models.CharField(default='', max_length=300),
        ),
    ]
