# Generated by Django 3.1.7 on 2021-08-20 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_auto_20210820_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-price']},
        ),
        migrations.AddField(
            model_name='bid',
            name='bidCreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterOrderWithRespectTo(
            name='bid',
            order_with_respect_to=None,
        ),
    ]
