# Generated by Django 3.1.7 on 2021-08-21 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_auto_20210820_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='endDate',
            new_name='auctionEndDate',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='startDate',
        ),
        migrations.AddField(
            model_name='auction',
            name='trip_endDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='auction',
            name='trip_startDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='auction',
            name='tripDetails',
            field=models.CharField(default='', max_length=280),
        ),
    ]
