# Generated by Django 3.1.7 on 2021-08-23 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0013_auto_20210823_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='vehicle_type',
            new_name='auctionVehicleType',
        ),
    ]
