# Generated by Django 3.1.7 on 2021-08-30 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0019_auto_20210825_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('waypoint_Latitude', models.FloatField()),
                ('waypoint_Longitude', models.FloatField()),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.auction')),
            ],
            options={
                'ordering': ['-order'],
            },
        ),
    ]
