# Generated by Django 3.1.7 on 2021-08-31 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0021_waypoint_waypoint_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waypoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip', models.TextField(blank=True, null=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.auction')),
            ],
        ),
        migrations.DeleteModel(
            name='Waypoint',
        ),
    ]
