# Generated by Django 3.1.7 on 2021-09-01 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0022_auto_20210831_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='tripDetails',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='waypoints',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.auction', unique=True),
        ),
    ]
