# Generated by Django 3.1.7 on 2021-09-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0026_auto_20210902_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auctionVehicleType',
            field=models.CharField(choices=[('BOAT', 'Boat'), ('CARAVAN', 'Caravan'), ('CAR', 'Car'), ('TINYHOUSE', 'Tinyhouse')], default='BOAT', max_length=9, verbose_name='Vehicle Type'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('BOAT', 'Boat'), ('CARAVAN', 'Caravan'), ('CAR', 'Car'), ('TINYHOUSE', 'Tinyhouse')], default='BOAT', max_length=9, verbose_name='Vehicle Type'),
        ),
    ]
