# Generated by Django 3.2.7 on 2021-09-11 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0029_auto_20210904_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waypoints',
            name='auction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auction.auction'),
        ),
    ]
