# Generated by Django 3.2.7 on 2021-09-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0030_alter_waypoints_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='v_image2',
            field=models.ImageField(default='defaultVehicle.jpg', upload_to='', verbose_name='Vehicle Image2'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='v_image3',
            field=models.ImageField(default='defaultVehicle.jpg', upload_to='', verbose_name='Vehicle Image3'),
        ),
    ]
