# Generated by Django 3.2.7 on 2021-10-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0031_auto_20210911_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='minPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='auctionVehicleType',
            field=models.CharField(choices=[('BOAT', 'Boat'), ('CARAVAN', 'Caravan'), ('CAR', 'Car'), ('BUS', 'Bus'), ('WALK', 'Walk'), ('RUN', 'Run'), ('BICYCLE', 'Bicycle'), ('MOTORCYCLE', 'Motorcycle'), ('TINYHOUSE', 'Tinyhouse')], default='BOAT', max_length=10, verbose_name='Vehicle Type'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_description',
            field=models.CharField(max_length=2000, verbose_name='Vehicle Description (2000 characters max)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('BOAT', 'Boat'), ('CARAVAN', 'Caravan'), ('CAR', 'Car'), ('BUS', 'Bus'), ('WALK', 'Walk'), ('RUN', 'Run'), ('BICYCLE', 'Bicycle'), ('MOTORCYCLE', 'Motorcycle'), ('TINYHOUSE', 'Tinyhouse')], default='BOAT', max_length=10, verbose_name='Vehicle Type'),
        ),
    ]
