# Generated by Django 3.2.7 on 2021-10-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0032_auto_20211016_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auction_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
