# Generated by Django 3.2.7 on 2021-10-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0033_auction_auction_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='minPrice',
            field=models.IntegerField(default=0),
        ),
    ]
