# Generated by Django 3.2.7 on 2021-10-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0035_auction_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='v_image4',
            field=models.ImageField(default='defaultVehicle.jpg', upload_to='', verbose_name='Vehicle Image4'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='v_image5',
            field=models.ImageField(default='defaultVehicle.jpg', upload_to='', verbose_name='Vehicle Image5'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='v_image6',
            field=models.ImageField(default='defaultVehicle.jpg', upload_to='', verbose_name='Vehicle Image6'),
        ),
    ]
