# Generated by Django 3.2.7 on 2021-10-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0036_auto_20211018_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='tripDetails',
            field=models.TextField(default='', max_length=3000),
        ),
    ]
