# Generated by Django 3.2.7 on 2021-10-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0039_alter_auction_tripdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auction_brief',
            field=models.CharField(default='', max_length=180),
        ),
    ]
