# Generated by Django 3.2.7 on 2021-09-04 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='unread',
        ),
    ]
