# Generated by Django 3.2.7 on 2021-10-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_message_unread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.TextField(max_length=1500),
        ),
    ]
