# Generated by Django 3.2.7 on 2021-09-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='inboxfull',
            field=models.BooleanField(default=False),
        ),
    ]
