# Generated by Django 3.2.7 on 2021-09-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_inboxfull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='inboxfull',
            field=models.IntegerField(default=0),
        ),
    ]
