# Generated by Django 3.2.7 on 2021-10-25 12:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20211012_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=800, null=True, verbose_name='User Description (800 characters max)'),
        ),
    ]
