# Generated by Django 3.2.7 on 2021-10-25 12:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_profile_user_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_description',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_info',
            field=ckeditor.fields.RichTextField(blank=True, max_length=800, null=True, verbose_name='Profile Info (800 characters max)'),
        ),
    ]
